# Generated by Django 5.2.16 on 2026-08-01 20:21

import almonium_book_processor.catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blockalignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='source_file',
            field=models.FileField(blank=True, upload_to=almonium_book_processor.catalog.models.source_upload_path, validators=[django.core.validators.FileExtensionValidator(['epub', 'xml'])]),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('translate', 'Translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication')], max_length=20),
        ),
    ]
