# Generated by Django 5.2.16 on 2026-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_edition_published_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='cefr_target',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='confidence',
        ),
        migrations.AddField(
            model_name='edition',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.RenameField(
            model_name='work',
            old_name='first_published_year',
            new_name='publication_year',
        ),
        migrations.AlterField(
            model_name='edition',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
