# Generated by Django 5.2.16 on 2026-08-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_edition_cefr_target_remove_edition_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='language',
            field=models.CharField(
                choices=[
                    ('bg', 'Bulgarian (bg)'),
                    ('ca', 'Catalan (ca)'),
                    ('cs', 'Czech (cs)'),
                    ('da', 'Danish (da)'),
                    ('de', 'German (de)'),
                    ('el', 'Greek (el)'),
                    ('en', 'English (en)'),
                    ('es', 'Spanish (es)'),
                    ('et', 'Estonian (et)'),
                    ('fi', 'Finnish (fi)'),
                    ('fr', 'French (fr)'),
                    ('ga', 'Irish (ga)'),
                    ('hr', 'Croatian (hr)'),
                    ('hu', 'Hungarian (hu)'),
                    ('is', 'Icelandic (is)'),
                    ('it', 'Italian (it)'),
                    ('lt', 'Lithuanian (lt)'),
                    ('lv', 'Latvian (lv)'),
                    ('mt', 'Maltese (mt)'),
                    ('nl', 'Dutch (nl)'),
                    ('no', 'Norwegian (no)'),
                    ('pl', 'Polish (pl)'),
                    ('pt', 'Portuguese (pt)'),
                    ('ro', 'Romanian (ro)'),
                    ('ru', 'Russian (ru)'),
                    ('sk', 'Slovak (sk)'),
                    ('sl', 'Slovenian (sl)'),
                    ('sr', 'Serbian (sr)'),
                    ('sv', 'Swedish (sv)'),
                    ('tr', 'Turkish (tr)'),
                    ('uk', 'Ukrainian (uk)'),
                ],
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name='work',
            name='original_language',
            field=models.CharField(
                choices=[
                    ('bg', 'Bulgarian (bg)'),
                    ('ca', 'Catalan (ca)'),
                    ('cs', 'Czech (cs)'),
                    ('da', 'Danish (da)'),
                    ('de', 'German (de)'),
                    ('el', 'Greek (el)'),
                    ('en', 'English (en)'),
                    ('es', 'Spanish (es)'),
                    ('et', 'Estonian (et)'),
                    ('fi', 'Finnish (fi)'),
                    ('fr', 'French (fr)'),
                    ('ga', 'Irish (ga)'),
                    ('hr', 'Croatian (hr)'),
                    ('hu', 'Hungarian (hu)'),
                    ('is', 'Icelandic (is)'),
                    ('it', 'Italian (it)'),
                    ('lt', 'Lithuanian (lt)'),
                    ('lv', 'Latvian (lv)'),
                    ('mt', 'Maltese (mt)'),
                    ('nl', 'Dutch (nl)'),
                    ('no', 'Norwegian (no)'),
                    ('pl', 'Polish (pl)'),
                    ('pt', 'Portuguese (pt)'),
                    ('ro', 'Romanian (ro)'),
                    ('ru', 'Russian (ru)'),
                    ('sk', 'Slovak (sk)'),
                    ('sl', 'Slovenian (sl)'),
                    ('sr', 'Serbian (sr)'),
                    ('sv', 'Swedish (sv)'),
                    ('tr', 'Turkish (tr)'),
                    ('uk', 'Ukrainian (uk)'),
                ],
                max_length=35,
            ),
        ),
    ]
