# Generated by Django 5.2.16 on 2026-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public catalog'), ('private', 'Private import')], default='public', max_length=10),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['work', 'status'], name='catalog_edi_work_id_c641e9_idx'),
        ),
    ]
