# Generated by Django 5.2.16 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_work_description_work_owner_id_work_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='owner_label',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
