# Generated by Django 5.2.16 on 2026-08-23 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_work_owner_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_block_id', models.CharField(max_length=80)),
                ('previous_text', models.TextField()),
                ('revised_text', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='catalog.contentblock')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_revisions', to='catalog.edition')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_block_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlignmentGroupReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField()),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('repaired', 'Manually repaired')], max_length=20)),
                ('source_block_ids', models.JSONField(default=list)),
                ('target_block_ids', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_group_reviews', to=settings.AUTH_USER_MODEL)),
                ('target_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_group_reviews', to='catalog.edition')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('target_edition', 'group_id'), name='catalog_alignment_review_edition_group_unique')],
            },
        ),
    ]
