# Generated by Django 5.2.16 on 2026-08-23 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_contentblockrevision_alignmentgroupreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='input_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='airun',
            name='reasoning_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alignmentgroupreview',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('repaired', 'Manually repaired'), ('ai_accepted', 'AI accepted')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChapterAlignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('confidence', models.FloatField()),
                ('strategy', models.CharField(max_length=80)),
                ('source_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_alignments', to='catalog.chapter')),
                ('source_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_chapter_alignments', to='catalog.edition')),
                ('target_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_alignments', to='catalog.chapter')),
                ('target_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_chapter_alignments', to='catalog.edition')),
            ],
            options={
                'ordering': ['target_edition', 'target_chapter__sequence', 'source_chapter__sequence'],
                'indexes': [models.Index(fields=['source_edition', 'target_edition', 'confidence'], name='catalog_cha_source__6667c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_edition', 'target_edition', 'source_chapter', 'target_chapter'), name='catalog_alignment_chapter_pair_unique')],
            },
        ),
    ]
