# Generated by Django 5.2.16 on 2026-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_textqualityfinding_artifact_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='parallel_role',
            field=models.CharField(choices=[('canonical', 'Canonical original'), ('parallel', 'Parallel edition'), ('standalone', 'Standalone edition')], default='canonical', help_text='Canonical editions root the block tree. Parallel editions are generated block-for-block from the canonical text and can be read side by side. Standalone editions are read on their own and are never block-synchronised.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['align_group'], name='catalog_block_align_group_idx'),
        ),
    ]
