# Generated by Django 5.2.16 on 2026-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_backfill_parallel_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='metadata_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='metadata_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('metadata', 'Metadata detection'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('lexical', 'Lexical analysis'), ('source_qa', 'Source text QA'), ('translate', 'Translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication')], max_length=20),
        ),
    ]
