# Generated by Django 5.2.16 on 2026-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_private_import_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='metadata_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
