# Generated by Django 5.2.16 on 2026-09-06 19:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_work_metadata_confirmed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='catalog.edition'),
        ),
        migrations.AlterField(
            model_name='airun',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='catalog.pipelinerun'),
        ),
        migrations.CreateModel(
            name='EditionTombstone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edition_id', models.UUIDField(unique=True)),
                ('edition_slug', models.SlugField(max_length=180)),
                ('work_slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=35)),
                ('edition_type', models.CharField(max_length=32)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('was_published', models.BooleanField(default=False)),
                ('published_book_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('copyright', 'Copyright claim'), ('owner_request', 'Owner request'), ('mistake', 'Uploaded in error'), ('superseded', 'Superseded by another edition'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('purged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_tombstones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purged_at'],
            },
        ),
        migrations.AddField(
            model_name='airun',
            name='tombstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='catalog.editiontombstone'),
        ),
    ]
