# Generated by Django 5.2.16 on 2026-09-06 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_purge_editions_keep_ai_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='withdrawal_reason',
            field=models.CharField(blank=True, choices=[('copyright', 'Copyright claim'), ('owner_request', 'Owner request'), ('mistake', 'Uploaded in error'), ('superseded', 'Superseded by another edition'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='edition',
            name='withdrawal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='withdrawal_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
