# Generated by Django 5.2.16 on 2026-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_removal_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='language',
            field=models.CharField(choices=[('bg', 'Bulgarian (bg)'), ('ca', 'Catalan (ca)'), ('cs', 'Czech (cs)'), ('da', 'Danish (da)'), ('de', 'German (de)'), ('el', 'Greek (el)'), ('en', 'English (en)'), ('es', 'Spanish (es)'), ('et', 'Estonian (et)'), ('fi', 'Finnish (fi)'), ('fr', 'French (fr)'), ('ga', 'Irish (ga)'), ('hr', 'Croatian (hr)'), ('hu', 'Hungarian (hu)'), ('is', 'Icelandic (is)'), ('it', 'Italian (it)'), ('ja', 'Japanese (ja)'), ('ko', 'Korean (ko)'), ('lt', 'Lithuanian (lt)'), ('lv', 'Latvian (lv)'), ('mk', 'Macedonian (mk)'), ('mt', 'Maltese (mt)'), ('nl', 'Dutch (nl)'), ('no', 'Norwegian (no)'), ('pl', 'Polish (pl)'), ('pt', 'Portuguese (pt)'), ('ro', 'Romanian (ro)'), ('ru', 'Russian (ru)'), ('sk', 'Slovak (sk)'), ('sl', 'Slovenian (sl)'), ('sr', 'Serbian (sr)'), ('sv', 'Swedish (sv)'), ('tr', 'Turkish (tr)'), ('uk', 'Ukrainian (uk)'), ('zh', 'Chinese (zh)')], max_length=35),
        ),
        migrations.AlterField(
            model_name='work',
            name='original_language',
            field=models.CharField(choices=[('bg', 'Bulgarian (bg)'), ('ca', 'Catalan (ca)'), ('cs', 'Czech (cs)'), ('da', 'Danish (da)'), ('de', 'German (de)'), ('el', 'Greek (el)'), ('en', 'English (en)'), ('es', 'Spanish (es)'), ('et', 'Estonian (et)'), ('fi', 'Finnish (fi)'), ('fr', 'French (fr)'), ('ga', 'Irish (ga)'), ('hr', 'Croatian (hr)'), ('hu', 'Hungarian (hu)'), ('is', 'Icelandic (is)'), ('it', 'Italian (it)'), ('ja', 'Japanese (ja)'), ('ko', 'Korean (ko)'), ('lt', 'Lithuanian (lt)'), ('lv', 'Latvian (lv)'), ('mk', 'Macedonian (mk)'), ('mt', 'Maltese (mt)'), ('nl', 'Dutch (nl)'), ('no', 'Norwegian (no)'), ('pl', 'Polish (pl)'), ('pt', 'Portuguese (pt)'), ('ro', 'Romanian (ro)'), ('ru', 'Russian (ru)'), ('sk', 'Slovak (sk)'), ('sl', 'Slovenian (sl)'), ('sr', 'Serbian (sr)'), ('sv', 'Swedish (sv)'), ('tr', 'Turkish (tr)'), ('uk', 'Ukrainian (uk)'), ('zh', 'Chinese (zh)')], max_length=35),
        ),
    ]
