# Generated by Django 5.2.16 on 2026-09-13 15:11

from django.db import migrations, models


def backfill_register(apps, schema_editor):
    Edition = apps.get_model("catalog", "Edition")
    for register in ("contemporary neutral", "period-faithful", "lightly modernised"):
        Edition.objects.using(schema_editor.connection.alias).filter(
            edition_type="machine_translation", translator=f"AI ({register})"
        ).update(literary_register=register)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_language_choices_spacy_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="literary_register",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contemporary neutral", "Contemporary neutral"),
                    ("period-faithful", "Period-faithful"),
                    ("lightly modernised", "Lightly modernised"),
                ],
                help_text="Generation register; blank means unknown or not applicable.",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_register, migrations.RunPython.noop),
    ]
