# Generated by Django 5.2.16 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_edition_literary_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="external_job_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="auto_publish",
            field=models.BooleanField(default=False),
        ),
    ]
