# Generated by Django 5.2.16 on 2026-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_edition_external_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('metadata', 'Metadata detection'), ('chapter_analysis', 'Chapter analysis'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('lexical', 'Lexical analysis'), ('source_qa', 'Source text QA'), ('translate', 'Translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication')], max_length=20),
        ),
    ]
