# Generated by Django 5.2.16 on 2026-09-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_chapter_analysis_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='analysis_role',
            field=models.CharField(choices=[('body', 'Substantive chapter'), ('front', 'Front matter'), ('back', 'Back matter')], default='body', help_text='Only substantive chapters contribute to the book difficulty estimate.', max_length=10),
        ),
        migrations.AddField(
            model_name='editionartifact',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='catalog.chapter'),
        ),
    ]
