# Generated by Django 5.2.16 on 2026-09-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_chapter_analysis_artifacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionartifact',
            name='kind',
            field=models.CharField(choices=[('lexical_profile', 'Lexical profile'), ('useful_words', 'Useful words'), ('source_qa', 'Source text QA'), ('difficulty', 'Difficulty assessment'), ('description', 'Generated description'), ('chapter_summary', 'Chapter summary'), ('quiz', 'Quiz'), ('sentence_alignment', 'Pair-specific sentence alignment')], max_length=40),
        ),
    ]
