# Generated by Django 5.2.16 on 2026-09-16 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_editionartifact_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=40, unique=True)),
                ('base_url', models.URLField(help_text="The target's origin, such as https://staging.books.almonium.com", max_length=500)),
                ('token', models.CharField(help_text="An API token created under Auth Token on the target's admin site.", max_length=200)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='promoted_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edition',
            name='promotion_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('metadata', 'Metadata detection'), ('chapter_analysis', 'Chapter analysis'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('lexical', 'Lexical analysis'), ('source_qa', 'Source text QA'), ('translate', 'Translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication'), ('promote', 'Promotion')], max_length=20),
        ),
    ]
