# Generated by Django 5.2.16 on 2026-09-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionTarget',
        ),
    ]
