# Generated by Django 5.2.16 on 2026-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_level_out_of_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='description',
            field=models.TextField(blank=True, help_text="The blurb in this edition's language; blank means the work's own."),
        ),
        migrations.AlterField(
            model_name='editionartifact',
            name='kind',
            field=models.CharField(choices=[('lexical_profile', 'Lexical profile'), ('useful_words', 'Useful words'), ('source_qa', 'Source text QA'), ('difficulty', 'Difficulty assessment'), ('description', 'Generated description'), ('chapter_summary', 'Chapter summary'), ('chapter_summary_translation', 'Translated chapter summary'), ('quiz', 'Quiz'), ('sentence_alignment', 'Pair-specific sentence alignment')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('metadata', 'Metadata detection'), ('chapter_analysis', 'Chapter analysis'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('lexical', 'Lexical analysis'), ('source_qa', 'Source text QA'), ('translate', 'Translation'), ('translate_metadata', 'Metadata translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication'), ('promote', 'Promotion')], max_length=20),
        ),
    ]
