# Generated by Django 5.2.16 on 2026-09-23 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_calm_shouting_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Source ingestion'), ('metadata', 'Metadata detection'), ('chapter_analysis', 'Chapter analysis'), ('sentences', 'Sentence splitting'), ('align', 'Alignment'), ('lexical', 'Lexical analysis'), ('glosses', 'Contextual glosses'), ('source_qa', 'Source text QA'), ('translate', 'Translation'), ('translate_metadata', 'Metadata translation'), ('adapt', 'Level adaptation'), ('publish', 'Publication'), ('promote', 'Promotion')], max_length=20),
        ),
        migrations.CreateModel(
            name='GlossNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text_hash', models.CharField(max_length=64)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('quote', models.TextField()),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='catalog.contentblock')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='catalog.chapter')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='catalog.edition')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosses', to='catalog.pipelinerun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_glosses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter__sequence', 'block__sequence', 'start_offset', 'created_at'],
                'indexes': [models.Index(fields=['edition', 'status', 'chapter'], name='catalog_glo_edition_d4c450_idx')],
            },
        ),
    ]
