from django.urls import path

from almonium_book_processor.catalog import views
from almonium_book_processor.catalog.activity import (
    catalogue_activity_view,
    edition_activity,
    removed_activity_view,
)
from almonium_book_processor.catalog.sentence_preview_views import (
    queue_sentence_alignment,
    sentence_preview,
)

app_name = "catalog"

urlpatterns = [
    path(
        "editions/<uuid:edition_id>/adaptation-pilot/<uuid:run_id>/apply/",
        views.apply_adaptation_pilot,
        name="apply-adaptation-pilot",
    ),
    path(
        "editions/<uuid:edition_id>/sentence-preview/<uuid:other_id>/",
        sentence_preview,
        name="sentence-preview",
    ),
    path(
        "editions/<uuid:edition_id>/sentence-alignment/<uuid:other_id>/queue/",
        queue_sentence_alignment,
        name="queue-sentence-alignment",
    ),
    path(
        "editions/<uuid:edition_id>/adaptation/queue/",
        views.queue_book_adaptation,
        name="queue-book-adaptation",
    ),
    path(
        "editions/<uuid:edition_id>/adaptation-floor/probe/",
        views.queue_floor_probe,
        name="queue-floor-probe",
    ),
    path(
        "editions/<uuid:edition_id>/fidelity-audit/queue/",
        views.queue_fidelity_audit,
        name="queue-fidelity-audit",
    ),
    path(
        "editions/<uuid:edition_id>/fidelity-audit/apply-all/",
        views.apply_fidelity_findings_view,
        name="apply-fidelity-findings",
    ),
    path(
        "editions/<uuid:edition_id>/fidelity-audit/dismiss-all/",
        views.dismiss_fidelity_findings_view,
        name="dismiss-fidelity-findings",
    ),
    path(
        "editions/<uuid:edition_id>/adaptation-pilot/queue/",
        views.queue_adaptation_pilot,
        name="queue-adaptation-pilot",
    ),
    path(
        "editions/<uuid:edition_id>/adaptation-pilot/<uuid:run_id>/",
        views.adaptation_pilot,
        name="adaptation-pilot",
    ),
    path(
        "editions/<uuid:edition_id>/chapter-analysis/project/",
        views.refresh_chapter_projections,
        name="refresh-chapter-projections",
    ),
    path(
        "editions/<uuid:edition_id>/chapters/<uuid:chapter_id>/analysis-role/",
        views.update_chapter_role,
        name="update-chapter-role",
    ),
    path("", views.dashboard, name="dashboard"),
    path("activity/", catalogue_activity_view, name="catalogue-activity"),
    path("activity/removed/", removed_activity_view, name="removed-activity"),
    path("editions/<uuid:edition_id>/activity/", edition_activity, name="edition-activity"),
    path("imports/private/", views.private_imports, name="private-imports"),
    path("removed/", views.removed_books, name="removed-books"),
    path("upload/", views.upload_source, name="upload"),
    path("imports/legacy/", views.import_legacy, name="import-legacy"),
    path("editions/<uuid:edition_id>/", views.edition_detail, name="edition-detail"),
    path("editions/<uuid:edition_id>/reader/", views.edition_reader, name="edition-reader"),
    path(
        "editions/<uuid:edition_id>/chapter-analysis/queue/",
        views.queue_chapter_analysis,
        name="queue-chapter-analysis",
    ),
    path(
        "editions/<uuid:edition_id>/metadata/translate/",
        views.queue_metadata_translation_view,
        name="queue-metadata-translation",
    ),
    path(
        "editions/<uuid:edition_id>/metadata/confirm/",
        views.confirm_edition_metadata,
        name="confirm-edition-metadata",
    ),
    path(
        "editions/<uuid:edition_id>/metadata/detect/",
        views.queue_metadata_detection,
        name="queue-metadata-detection",
    ),
    path(
        "editions/<uuid:edition_id>/blocks/<uuid:block_id>/edit/",
        views.edit_block_text,
        name="edit-block-text",
    ),
    path(
        "editions/<uuid:edition_id>/blocks/<uuid:block_id>/remove/",
        views.remove_block_view,
        name="remove-block",
    ),
    path(
        "editions/<uuid:edition_id>/lexical/queue/",
        views.queue_lexical_analysis,
        name="queue-lexical-analysis",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/queue/",
        views.queue_source_quality_scan,
        name="queue-source-quality-scan",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/detached-initials/approve/",
        views.approve_detached_initials,
        name="approve-detached-initials",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/<uuid:finding_id>/apply/",
        views.apply_source_quality_finding,
        name="apply-source-quality-finding",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/<uuid:finding_id>/reopen/",
        views.reopen_source_quality_finding,
        name="reopen-source-quality-finding",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/<uuid:finding_id>/edit-block/",
        views.edit_finding_block,
        name="edit-finding-block",
    ),
    path(
        "editions/<uuid:edition_id>/source-qa/<uuid:finding_id>/dismiss/",
        views.dismiss_source_quality_finding,
        name="dismiss-source-quality-finding",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/",
        views.alignment_review,
        name="alignment-review",
    ),
    path(
        "editions/<uuid:edition_id>/alignment/queue/",
        views.queue_source_alignment,
        name="queue-source-alignment",
    ),
    path(
        "editions/<uuid:edition_id>/translate/queue/",
        views.queue_parallel_translation,
        name="queue-parallel-translation",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/ai/queue/",
        views.queue_ai_alignment_review,
        name="queue-ai-alignment-review",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/ai/confirm-safe/",
        views.confirm_ai_safe_alignments,
        name="confirm-ai-safe-alignments",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/groups/<uuid:group_id>/accept/",
        views.accept_alignment_group,
        name="accept-alignment-group",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/chapters/accept/",
        views.accept_alignment_chapter,
        name="accept-alignment-chapter",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/repair/",
        views.repair_alignment,
        name="repair-alignment",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/gaps/<uuid:source_block_id>/translate/",
        views.translate_alignment_gap,
        name="translate-alignment-gap",
    ),
    path(
        "editions/<uuid:edition_id>/alignment-review/blocks/<uuid:block_id>/edit/",
        views.edit_alignment_target,
        name="edit-alignment-target",
    ),
    path(
        "editions/<uuid:edition_id>/warnings/<uuid:warning_id>/resolve/",
        views.resolve_warning,
        name="resolve-warning",
    ),
    path(
        "editions/<uuid:edition_id>/warnings/resolve-all/",
        views.resolve_warnings_by_code,
        name="resolve-warnings-by-code",
    ),
    path(
        "editions/<uuid:edition_id>/review/complete/",
        views.complete_edition_review,
        name="complete-edition-review",
    ),
    path(
        "editions/<uuid:edition_id>/publish/",
        views.publish_edition_to_almonium,
        name="publish-edition",
    ),
    path(
        "editions/<uuid:edition_id>/promote/",
        views.promote_edition_view,
        name="promote-edition",
    ),
    path(
        "editions/<uuid:edition_id>/purge/",
        views.purge_edition_view,
        name="purge-edition",
    ),
    path(
        "editions/<uuid:edition_id>/retry/",
        views.retry_failed_edition,
        name="retry-edition",
    ),
    path(
        "editions/<uuid:edition_id>/release-private/",
        views.release_private_import_to_owner,
        name="release-private-import",
    ),
]
